apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-web
  template:
    metadata:
      labels:
        app: express-web
    spec:
      containers:
        - name: web
          image: fdai7814/express-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000